### PR TITLE
Fix connection error

### LINKED ISSUE #83: Better handling of imagefactory connection error
If imagefactory connection fails, this error is raised in create_factory_provider_image and create_factory_target_image:

Connection refused - connect(2)
/usr/share/ruby/net/http.rb:762:in `initialize'
 /usr/share/ruby/net/http.rb:762:in`open'
 /usr/share/ruby/net/http.rb:762:in `block in connect'
 /usr/share/ruby/timeout.rb:54:in`timeout'
 /usr/share/ruby/timeout.rb:99:in `timeout'
 /usr/share/ruby/net/http.rb:762:in`connect'
 /usr/share/ruby/net/http.rb:755:in `do_start'
 /usr/share/ruby/net/http.rb:744:in`start'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/webmock-1.8.7/lib/webmock/http_lib_adapters/net_http.rb:90:in `request_with_webmock'
 /usr/share/ruby/net/http.rb:1307:in`send_entity'
 /usr/share/ruby/net/http.rb:1096:in `post'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/connection.rb:113:in`block in request'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in `block in instrument'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in `instrument'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/connection.rb:110:in`request'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/bundler/gems/aeolus-image-rubygem-4bffe3f60ce3/lib/aeolus_image/active_resource_oauth_client.rb:30:in `request_with_oauth'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/connection.rb:98:in`block in post'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/connection.rb:218:in `with_auth'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/connection.rb:98:in`post'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/base.rb:1360:in `create'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/observing.rb:19:in`create_with_notifications'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/base.rb:1155:in `save'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/validations.rb:79:in`save_with_validation'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/observing.rb:19:in `save_with_notifications'
 /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activeresource-3.2.8/lib/active_resource/base.rb:1172:in`save!'
 /home/jprovazn/devel/tim/app/models/tim/provider_image.rb:47:in `create_factory_provider_image'

More descriptive error instead of "Connection refused - connect(2)" should be returned.
I think this should be fixed before 2.0 release.

### PR DESCRIPTION
**Pull request by mtaylor**
Return custom Exception on Factory Connection Refused

Raises a more appropriate exception when Tim can not
connect to ImageFactory.

Fixes: https://github.com/aeolus-incubator/tim/issues/83

### CODE REVIEW

File: lib/tim/engine.rb [hunk 1]
```diff
@@ -16,6 +16,11 @@ class Engine < Rails::Engine
       Dir[Tim::Engine.root.join('app', 'patches', '**', '*.rb')].each do |p|
         require p
       end
+
+      # Load Exceptions
+      Dir[Tim::Engine.root.join('app', 'exceptions', '**', '*.rb')].each do |e|
```
Comment (jguiditta) [inline lib/tim/engine.rb:21]: I'll leave this as a comment, maybe we can make an issue to clean this up next sprint (I made about the same comment on another recent 'blocker' patch, and let it go there too).  It seems very redundant to me to have 3 blocks now, each for just adding a directory to the load path.  This can easily be accomplished in a single block, making it more DRY.

**Comment by jguiditta** [comment]
comment aside, this does seem to resolve the described issue
